New-ADGroup -name "DG_CAFE" -GroupCategory Security -GroupScope Global -DisplayName "CAFE" -Path "OU=OU_CAFE,DC=HC04,DC=local" -Description "CAFE user group"
New-ADGroup -name "DG_CUSTODIAL" -GroupCategory Security -GroupScope Global -DisplayName "CUSTODIAL" -Path "OU=OU_CUSTODIAL,DC=HC04,DC=local" -Description "CUSTODIAL user group"
New-ADGroup -name "DG_EDUCATION" -GroupCategory Security -GroupScope Global -DisplayName "EDUCATION" -Path "OU=OU_EDUCATION,DC=HC04,DC=local" -Description "EDUCATION user group"
New-ADGroup -name "DG_ENGINEERING" -GroupCategory Security -GroupScope Global -DisplayName "ENGINEERING" -Path "OU=OU_ENGINEERING,DC=HC04,DC=local" -Description "ENGINEERING user group"
New-ADGroup -name "DG_FINANCE" -GroupCategory Security -GroupScope Global -DisplayName "FINANCE" -Path "OU=OU_FINANCE,DC=HC04,DC=local" -Description "FINANCE user group"
New-ADGroup -name "DG_HR" -GroupCategory Security -GroupScope Global -DisplayName "HR" -Path "OU=OU_HR,DC=HC04,DC=local" -Description "HR user group"
New-ADGroup -name "DG_IT" -GroupCategory Security -GroupScope Global -DisplayName "IT Admins" -Path "OU=OU_IT,DC=HC04,DC=local" -Description "IT Admin user group"
New-ADGroup -name "DG_MARKETING" -GroupCategory Security -GroupScope Global -DisplayName "MARKETING" -Path "OU=OU_MARKETING,DC=HC04,DC=local" -Description "MARKETING user group"
New-ADGroup -name "DG_MGRS" -GroupCategory Security -GroupScope Global -DisplayName "MGRS" -Path "OU=OU_MGRS,DC=HC04,DC=local" -Description "MGRS user group"
New-ADGroup -name "DG_PHYSICAL" -GroupCategory Security -GroupScope Global -DisplayName "PHYSICAL" -Path "OU=OU_PHYSICAL,DC=HC04,DC=local" -Description "PHYSICAL user group"
New-ADGroup -name "DG_PRODUCTION" -GroupCategory Security -GroupScope Global -DisplayName "PRODUCTION" -Path "OU=OU_PRODUCTION,DC=HC04,DC=local" -Description "PRODUCTION user group"
New-ADGroup -name "DG_QUALITY" -GroupCategory Security -GroupScope Global -DisplayName "QUALITY" -Path "OU=OU_QUALITY,DC=HC04,DC=local" -Description "QUALITY user group"
New-ADGroup -name "DG_SALES" -GroupCategory Security -GroupScope Global -DisplayName "SALES" -Path "OU=OU_SALES,DC=HC04,DC=local" -Description "SALES user group"
New-ADGroup -name "DG_EXECUTIVES" -GroupCategory Security -GroupScope Global -DisplayName "EXECUTIVE" -Path "OU=OU_EXECUTIVES,DC=HC04,DC=local" -Description "EXECUTIVES user group"