net user PierceA1 pw /add /domain 
net user AllniteS1 pw /add /domain 
net user ForallR1 pw /add /domain 
net user AbiteM1 pw /add /domain 
net user ByteZ1 pw /add /domain 
net user ByteE1 pw /add /domain 
net user ByteG1 pw /add /domain 
net user UldmeH1 pw /add /domain 
net user MeeH1 pw /add /domain 
net user PefullyH1 pw /add /domain 
net user MaloneH1 pw /add /domain 
net user LottamoreH1 pw /add /domain 
net user LotashakinH1 pw /add /domain 
net user HummH1 pw /add /domain 
net user MowerH1 pw /add /domain 
net user ZitoffH1 pw /add /domain 
net user MicidelH1 pw /add /domain 
net user UmpaigeH1 pw /add /domain 
net user UckupH1 pw /add /domain 
net user EmroomH1 pw /add /domain 
net user TellsallH1 pw /add /domain 